name: 'Set persistent value'
description: 'Sets a value that persists through GitHub Actions jobs and workflows.'
branding:
  icon: 'save'
  color: 'orange'
inputs:
  access_token:
    description: 'Your access token (see README.md on how to get one).'
    required: true
  key:
    description: "The key to retrieve the value with."
    required: false
  value:
    description: "The value to be stored."
    required: false
  json:
    description: "The value(s) to be stored"
    required: false
outputs:
  value:
    description: "The value that was stored."
runs:
  using: "node16"
  main: "dist/index.js"
