name: 'Set persistent value'
description: 'Sets a value that persists through GitHub Actions jobs and workflows.'
branding:
  icon: 'save'
  color: 'orange'
inputs:
  unique_key:
    description: 'Your secret unique key (see README.md on how to get one).'
    required: true
  key:
    description: "The key to retrieve the value with."
    required: true
  value:
    description: "The value to be stored."
    required: true
outputs:
  value:
    description: "The value that was stored."
runs:
  using: "node12"
  main: "dist/index.js"
