on: workflow_dispatch

jobs:
  set_persistent_value_job:
    runs-on: ubuntu-latest
    name: Set multiple persistent values
    steps:
      - name: Set a persistent value
        id: set_persistent_value_step
        uses: aaimio/set-persistent-value@master
        with:
          json: '{ "some_key": 42, "foo": "bar", "boolean_value": true }'
          access_token: ${{ secrets.ACCESS_TOKEN }}
      - name: Announce if value were set successfully
        if: steps.set_persistent_value_step.outputs.success == 'true'
        run: echo "The value were set."
